import { DndContext } from "@dnd-kit/core";
import { GeistSans } from "geist/font/sans";

import "./globals.css";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={GeistSans.className}>
            <body className="w-svh">{children}</body>
        </html>
    );
}
